const mongoose = require('mongoose');

const studentSchema = new mongoose.Schema({

  // Link with User account
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    unique: true
  },

  // Student basic details
  name: {
    type: String,
    required: [true, 'Student name is required'],
    trim: true
  },

  email: {
    type: String,
    required: [true, 'Student email is required'],
    lowercase: true,
    trim: true
  },

  rollNumber: {
    type: String,
    required: [true, 'Roll number is required'],
    unique: true,
    trim: true,
    uppercase: true
  },

  /////////////////////////////////////////////////////////////
  // FACE AUTHENTICATION
  /////////////////////////////////////////////////////////////

  faceDescriptor: {
    type: [Number], // 128 numbers from face-api.js
    default: null
  },

  /////////////////////////////////////////////////////////////
  // MOBILE APP SECURITY (FLUTTER)
  /////////////////////////////////////////////////////////////

  phoneNumber: {
    type: String,
    trim: true,
    default: null
  },

  mobileRegistered: {
    type: Boolean,
    default: false
  },

  // Android ID / iPhone IDFV
  deviceSystemId: {
    type: String,
    default: null
  },

  // Permanent BLE ID generated by app
  permanentId: {
    type: String,
    unique: true,
    sparse: true,
    default: () => 'PENDING_' + new mongoose.Types.ObjectId()
  },

  // Prevent login from another phone
  activeSession: {
    type: Boolean,
    default: false
  },

  /////////////////////////////////////////////////////////////
  // STUDENT CLASS DETAILS
  /////////////////////////////////////////////////////////////

  studentClass: {
    type: String,
    enum: [
      'CCE', 'IT', 'CSBS', 'MECH', 'EEE', 'AIML',
      'CSE-A', 'CSE-B', 'CSE-C', 'CSE-CYS',
      'ECE-A', 'ECE-B', 'ECE-C',
      'AIDS-A', 'AIDS-B', 'AIDS-C', 'AIDS-D'
    ],
    required: [true, 'Class is required'],
    trim: true
  },

  year: {
    type: String,
    enum: ['I', 'II', 'III', 'IV'],
    required: [true, 'Year is required'],
    trim: true
  },

  /////////////////////////////////////////////////////////////
  // TIMESTAMP
  /////////////////////////////////////////////////////////////

  createdAt: {
    type: Date,
    default: Date.now
  }

});

module.exports = mongoose.model('Student', studentSchema);